kind: Deployment
apiVersion: apps/v1
metadata:
  name: sushiweb
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: sushiweb
          image: quay.io/schabrolles/sushiweb:prod
